/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tayre
 */
public class QuizView extends javax.swing.JFrame {
    private QuizModel theModel;
    private QuizController theController;


    /**
     * Creates new form QuizView1
     */
    public QuizView(QuizModel theModel) {

        initComponents();
        this.theModel = theModel;
        
         hideAllOptions();


    }
    
    public void displayQuestion(){
        
    }
    
        public void showRadioButtons() {
        jRadioButtonA.setVisible(true);
        jRadioButtonB.setVisible(true);
        jRadioButtonC.setVisible(true);
        jRadioButtonD.setVisible(true);
        jCheckBoxA.setVisible(false);
        jCheckBoxB.setVisible(false);
        jCheckBoxC.setVisible(false);
        jCheckBoxD.setVisible(false);
    }

    public void showCheckBoxes() {
        jRadioButtonA.setVisible(false);
        jRadioButtonB.setVisible(false);
        jRadioButtonC.setVisible(false);
        jRadioButtonD.setVisible(false);
        jCheckBoxA.setVisible(true);
        jCheckBoxB.setVisible(true);
        jCheckBoxC.setVisible(true);
        jCheckBoxD.setVisible(true);
    }

    public void hideAllOptions() {
        jRadioButtonA.setVisible(false);
        jRadioButtonB.setVisible(false);
        jRadioButtonC.setVisible(false);
        jRadioButtonD.setVisible(false);
        jCheckBoxA.setVisible(false);
        jCheckBoxB.setVisible(false);
        jCheckBoxC.setVisible(false);
        jCheckBoxD.setVisible(false);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQuestionText = new javax.swing.JLabel();
        jLabelQuestionCount = new javax.swing.JLabel();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jRadioButtonD = new javax.swing.JRadioButton();
        jCheckBoxA = new javax.swing.JCheckBox();
        jCheckBoxB = new javax.swing.JCheckBox();
        jCheckBoxC = new javax.swing.JCheckBox();
        jCheckBoxD = new javax.swing.JCheckBox();
        jButtonPrev = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabelFeedback = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuITem = new javax.swing.JMenu();
        jMenuItemXML = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelQuestionText.setText("jLabel1");

        jLabelQuestionCount.setText("jLabel2");

        jRadioButtonA.setText("jRadioButton1");

        jRadioButtonB.setText("jRadioButton2");

        jRadioButtonC.setText("jRadioButton3");

        jRadioButtonD.setText("jRadioButton4");

        jCheckBoxA.setText("jCheckBox1");

        jCheckBoxB.setText("jCheckBox2");

        jCheckBoxC.setText("jCheckBox3");

        jCheckBoxD.setText("jCheckBox4");

        jButtonPrev.setText("jButton1");
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });

        jButtonSubmit.setText("jButton2");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonNext.setText("jButton3");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabelFeedback.setText("jLabel1");

        jMenuITem.setText("File");

        jMenuItemXML.setText("jMenuItem1");
        jMenuItemXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemXMLActionPerformed(evt);
            }
        });
        jMenuITem.add(jMenuItemXML);

        jMenuItem2.setText("jMenuItem2");
        jMenuITem.add(jMenuItem2);

        jMenuBar1.add(jMenuITem);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabelQuestionCount, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonB)
                            .addComponent(jRadioButtonC)
                            .addComponent(jRadioButtonD)
                            .addComponent(jRadioButtonA)
                            .addComponent(jCheckBoxA, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxC, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFeedback)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jButtonPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelQuestionCount)
                .addGap(18, 18, 18)
                .addComponent(jLabelQuestionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxA)
                .addGap(5, 5, 5)
                .addComponent(jRadioButtonB)
                .addGap(7, 7, 7)
                .addComponent(jCheckBoxB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonC)
                .addGap(8, 8, 8)
                .addComponent(jCheckBoxC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxD)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrev)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButtonNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFeedback)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jMenuItemXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemXMLActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckBoxA;
    private javax.swing.JCheckBox jCheckBoxB;
    private javax.swing.JCheckBox jCheckBoxC;
    private javax.swing.JCheckBox jCheckBoxD;
    private javax.swing.JLabel jLabelFeedback;
    private javax.swing.JLabel jLabelQuestionCount;
    private javax.swing.JLabel jLabelQuestionText;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuITem;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemXML;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonB;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonD;
    // End of variables declaration//GEN-END:variables
void addPrevListener(ActionListener listenForPrevButton){
        jButtonPrev.addActionListener(listenForPrevButton);
    }
    
    void addNextListener(ActionListener listenForNextButton){
        jButtonNext.addActionListener(listenForNextButton);
    }
    
    void addSubmitListener(ActionListener listenForSubmitButton){
        jButtonSubmit.addActionListener(listenForSubmitButton);
    }
    
    void addXmlListener(ActionListener listenForXMLButton){
        jMenuItemXML.addActionListener(listenForXMLButton);
    }
    
   /* void addViewBidsListener(ActionListener listenForViewBidsButton){
        jMenuItemViewBids.addActionListener(listenForViewBidsButton);
    }*/
   
    void displayErrorMessage(String errorMessage){
        JOptionPane.showMessageDialog(this, errorMessage);
    }
    
    void setQuestion(String text) {
        jLabelQuestionText.setText(text);
    }
    
    void setFeedback(String feedback) {
        jLabelFeedback.setText(feedback);
    }
    
    void setA(String a) {
        jRadioButtonA.setText(a);
    }
    
    void setB(String b) {
        jRadioButtonB.setText(b);
    }
    
    void setC(String c) {
        jRadioButtonC.setText(c);
    }
    
    void setD(String d) {
        jRadioButtonD.setText(d);
    }
    
    void setQuestionCount(String questionCount) {
        jLabelQuestionCount.setText(questionCount);
    }
    
    void updateQuizViewPanel(int currentQuestionNum, int questionCount) {
        setQuestionCount((1 + currentQuestionNum) + " of " 
                + questionCount + " questions");
    }
    
    void enablePrevButton() {
      jButtonPrev.setEnabled(true);
    }

    void enableNextButton() {
      jButtonNext.setEnabled(true);
    }
    
    void disablePrevButton() {
      jButtonPrev.setEnabled(false);
    }

    void disableNextButton() {
      jButtonNext.setEnabled(false);
    }
    
   /* public void addQuitListener(MouseListener listener) {
        jMenuQuit.addMouseListener(listener);
    } */

}
