/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tayre
 */
public class QuizView extends javax.swing.JFrame {
    private QuizModel theModel;
    private QuizController theController;


    /**
     * Creates new form QuizView1
     */
    public QuizView(QuizModel theModel) {

        initComponents();
        customInitcomponents();
        this.theModel = theModel;
        
         hideAllOptions();


    }
    
    public void displayQuestion(){
        
    }
    
        public void showRadioButtons() {
        jLabelStart.setVisible(false);
        jRadioButtonA.setVisible(true);
        jRadioButtonB.setVisible(true);
        jRadioButtonC.setVisible(true);
        jRadioButtonD.setVisible(true);
        jCheckBoxA.setVisible(false);
        jCheckBoxB.setVisible(false);
        jCheckBoxC.setVisible(false);
        jCheckBoxD.setVisible(false);
    }

    public void showCheckBoxes() {
        jLabelStart.setVisible(false);
        jRadioButtonA.setVisible(false);
        jRadioButtonB.setVisible(false);
        jRadioButtonC.setVisible(false);
        jRadioButtonD.setVisible(false);
        jCheckBoxA.setVisible(true);
        jCheckBoxB.setVisible(true);
        jCheckBoxC.setVisible(true);
        jCheckBoxD.setVisible(true);
    }

    public void hideAllOptions() {
        jRadioButtonA.setVisible(false);
        jRadioButtonB.setVisible(false);
        jRadioButtonC.setVisible(false);
        jRadioButtonD.setVisible(false);
        jCheckBoxA.setVisible(false);
        jCheckBoxB.setVisible(false);
        jCheckBoxC.setVisible(false);
        jCheckBoxD.setVisible(false);
        jButtonNext.setVisible(false);
        jButtonPrev.setVisible(false);
        jButtonSubmit.setVisible(false);
    }
    
    public void showButtons(){
        jButtonNext.setVisible(true);
        jButtonPrev.setVisible(true);
        jButtonSubmit.setVisible(true);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelQuestionText = new javax.swing.JLabel();
        jLabelQuestionCount = new javax.swing.JLabel();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jRadioButtonD = new javax.swing.JRadioButton();
        jCheckBoxA = new javax.swing.JCheckBox();
        jCheckBoxB = new javax.swing.JCheckBox();
        jCheckBoxC = new javax.swing.JCheckBox();
        jCheckBoxD = new javax.swing.JCheckBox();
        jButtonPrev = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jLabelFeedback = new javax.swing.JLabel();
        jLabelStart = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuITem = new javax.swing.JMenu();
        jMenuItemXML = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));

        jRadioButtonA.setBackground(new java.awt.Color(204, 255, 255));
        jRadioButtonA.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonA.setText("jRadioButton1");

        jRadioButtonB.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButtonB.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonB.setText("jRadioButton2");

        jRadioButtonC.setBackground(new java.awt.Color(153, 255, 204));
        jRadioButtonC.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonC.setText("jRadioButton3");

        jRadioButtonD.setBackground(new java.awt.Color(51, 255, 153));
        jRadioButtonD.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonD.setText("jRadioButton4");

        jCheckBoxA.setBackground(new java.awt.Color(255, 204, 255));
        jCheckBoxA.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxA.setText("jCheckBox1");

        jCheckBoxB.setBackground(new java.awt.Color(255, 153, 255));
        jCheckBoxB.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxB.setText("jCheckBox2");

        jCheckBoxC.setBackground(new java.awt.Color(255, 102, 255));
        jCheckBoxC.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxC.setText("jCheckBox3");

        jCheckBoxD.setBackground(new java.awt.Color(255, 0, 153));
        jCheckBoxD.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxD.setText("jCheckBox4");

        jButtonPrev.setBackground(new java.awt.Color(204, 255, 255));
        jButtonPrev.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPrev.setText("Prev");
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });

        jButtonSubmit.setBackground(new java.awt.Color(153, 255, 255));
        jButtonSubmit.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonNext.setBackground(new java.awt.Color(102, 255, 255));
        jButtonNext.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabelStart.setText("Welcome to my quiz! Select XML or JSON to begin :-)");

        jMenuITem.setText("File");

        jMenuItemXML.setText("jMenuItem1");
        jMenuItemXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemXMLActionPerformed(evt);
            }
        });
        jMenuITem.add(jMenuItemXML);

        jMenuItem2.setText("jMenuItem2");
        jMenuITem.add(jMenuItem2);

        jMenuBar1.add(jMenuITem);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabelStart, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelQuestionCount, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuestionText, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jButtonPrev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNext))
                            .addComponent(jLabelFeedback)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jRadioButtonB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jCheckBoxA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBoxD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jCheckBoxC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelQuestionCount)
                .addGap(18, 18, 18)
                .addComponent(jLabelQuestionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxA)
                .addGap(5, 5, 5)
                .addComponent(jRadioButtonB)
                .addGap(9, 9, 9)
                .addComponent(jCheckBoxB)
                .addGap(17, 17, 17)
                .addComponent(jRadioButtonC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxC)
                .addGap(11, 11, 11)
                .addComponent(jRadioButtonD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxD)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrev)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButtonNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabelFeedback)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jMenuItemXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemXMLActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckBoxA;
    private javax.swing.JCheckBox jCheckBoxB;
    private javax.swing.JCheckBox jCheckBoxC;
    private javax.swing.JCheckBox jCheckBoxD;
    private javax.swing.JLabel jLabelFeedback;
    private javax.swing.JLabel jLabelQuestionCount;
    private javax.swing.JLabel jLabelQuestionText;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuITem;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemXML;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonB;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonD;
    // End of variables declaration//GEN-END:variables
    private void customInitcomponents(){
        buttonGroup1.add(jRadioButtonA);
        buttonGroup1.add(jRadioButtonB);
        buttonGroup1.add(jRadioButtonC);
        buttonGroup1.add(jRadioButtonD);
    }
    
    void addPrevListener(ActionListener listenForPrevButton){
        jButtonPrev.addActionListener(listenForPrevButton);
    }
    
    void addNextListener(ActionListener listenForNextButton){
        jButtonNext.addActionListener(listenForNextButton);
    }
    
    void addSubmitListener(ActionListener listenForSubmitButton){
        jButtonSubmit.addActionListener(listenForSubmitButton);
    }
    
    void addXmlListener(ActionListener listenForXMLButton){
        jMenuItemXML.addActionListener(listenForXMLButton);
    }
    
   /* void addViewBidsListener(ActionListener listenForViewBidsButton){
        jMenuItemViewBids.addActionListener(listenForViewBidsButton);
    }*/
   
    void displayErrorMessage(String errorMessage){
        JOptionPane.showMessageDialog(this, errorMessage);
    }
    
    void setQuestion(String text) {
        jLabelQuestionText.setText(text);
    }
    
    void setFeedback(String feedback) {
        jLabelFeedback.setText(feedback);
    }
    
    void setA(String a) {
        jRadioButtonA.setText(a);
        jCheckBoxA.setText(a);
    }
    
    void setB(String b) {
        jRadioButtonB.setText(b);
        jCheckBoxB.setText(b);
    }
    
    void setC(String c) {
        jRadioButtonC.setText(c);
        jCheckBoxC.setText(c);
    }
    
    void setD(String d) {
        jRadioButtonD.setText(d);
        jCheckBoxD.setText(d);
    }
    
    
    void setQuestionCount(String questionCount) {
        jLabelQuestionCount.setText(questionCount);
    }
    
    void updateQuizViewPanel(int currentQuestionNum, int questionCount) {
        setQuestionCount((1 + currentQuestionNum) + " of " 
                + questionCount + " questions");
    }
    
    void enablePrevButton() {
      jButtonPrev.setEnabled(true);
    }

    void enableNextButton() {
      jButtonNext.setEnabled(true);
    }
    
    void disablePrevButton() {
      jButtonPrev.setEnabled(false);
    }

    void disableNextButton() {
      jButtonNext.setEnabled(false);
    }
    
    public void displayMessage(String message) {
        JOptionPane.showMessageDialog(QuizView.this, message);
    }

    
    public String getCurrentAnswer() {
    StringBuilder answer = new StringBuilder();
    if (jRadioButtonA.isVisible()) {
        if (jRadioButtonA.isSelected()) return "a";
        if (jRadioButtonB.isSelected()) return "b";
        if (jRadioButtonC.isSelected()) return "c";
        if (jRadioButtonD.isSelected()) return "d";
    } else if (jCheckBoxA.isVisible()) {
        if (jCheckBoxA.isSelected()) answer.append("a");
        if (jCheckBoxB.isSelected()) answer.append("b");
        if (jCheckBoxC.isSelected()) answer.append("c");
        if (jCheckBoxD.isSelected()) answer.append("d");
        return answer.toString();
    }
    return answer.toString(); // Returns empty string if no options are selected
}
    
 

public void setBackgroundColor(Color color) {
    getContentPane().setBackground(color);
}

public void resetRadioButtons() {
    buttonGroup1.clearSelection();
}


    
   /* public void addQuitListener(MouseListener listener) {
        jMenuQuit.addMouseListener(listener);
    } */

}
