/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quiz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author Tayla Rechichi
 */
public class ViewScores extends javax.swing.JDialog {

    /**
     * Creates new form ViewScores
     */
    private QuizModel theModel;
    
    public ViewScores(java.awt.Frame parent, boolean modal, QuizModel theModel) {
        super(parent, modal);
        initComponents();
        this.theModel = theModel;
        displayScoreInfo();
        setupNavigationListeners();

    }
    
    public void displayScoreInfo() {
        if (theModel.foundScores()){
            updateScoresDisplay(theModel.getTheScore());  
        
        if(theModel.getCurrentScoreNum() == 0){
            disablePrevButton();
        }else{
            enablePrevButton();
        }
        
        if (theModel.getCurrentScoreNum() == theModel.getScoreCount() - 1){
            disableNextButton();
        }else {
            enableNextButton();
        }
        }else {
              clearScoresDisplay();  
        }

    }

    private void updateScoresDisplay(Scores score) {
        jLabelName.setText(score.getName());
        jLabelScore.setText(score.getScore());
        jLabelDate.setText(score.getDate());
        jLabelTime.setText(score.getTimer());
    }

    private void clearScoresDisplay() {
        jLabelName.setText("");
        jLabelScore.setText("");
        jLabelDate.setText("");
        jLabelTime.setText("");
    }
     
    private void setupNavigationListeners() {
        jButtonNextScore.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                theModel.nextScore();
                displayScoreInfo(); // Refresh display with the next bid
            }
        });

        jButtonPrevScore.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                theModel.previousScore();
                displayScoreInfo(); // Refresh display with the previous bid
            }
        });
    }
    
    void enablePrevButton() {
      jButtonPrevScore.setEnabled(true);
    }

    void enableNextButton() {
      jButtonNextScore.setEnabled(true);
    }
    
    void disablePrevButton() {
      jButtonPrevScore.setEnabled(false);
    }

    void disableNextButton() {
      jButtonNextScore.setEnabled(false);
    }
    
     void addPrevScoresListener(ActionListener listenForPrevButton){
        jButtonPrevScore.addActionListener(listenForPrevButton);
    }
    
    void addNextScoresListener(ActionListener listenForNextButton){
        jButtonNextScore.addActionListener(listenForNextButton);
    }
    
    public void setName(String name) {
        jLabelName.setText(name);
    }
    
    public void setScore(String score) {
        jLabelScore.setText(score);
    }
    
    public void setDate(String date) {
        jLabelDate.setText(date);
    }
    
    public void setTimer(String timer) {
        jLabelTime.setText(timer);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jButtonPrevScore = new javax.swing.JButton();
        jButtonNextScore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setForeground(new java.awt.Color(255, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("All Results!");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Score:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Date & Time:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Completed in:");

        jLabelName.setForeground(new java.awt.Color(0, 0, 0));
        jLabelName.setText("jLabel6");

        jLabelScore.setForeground(new java.awt.Color(0, 0, 0));
        jLabelScore.setText("jLabel7");

        jLabelDate.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDate.setText("jLabel8");

        jLabelTime.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTime.setText("jLabel9");

        jButtonPrevScore.setBackground(new java.awt.Color(51, 255, 204));
        jButtonPrevScore.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPrevScore.setText("Prev");

        jButtonNextScore.setBackground(new java.awt.Color(102, 255, 204));
        jButtonNextScore.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNextScore.setText("Next");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonPrevScore)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNextScore)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName)
                    .addComponent(jLabelScore)
                    .addComponent(jLabelDate)
                    .addComponent(jLabelTime))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelTime))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevScore)
                    .addComponent(jButtonNextScore))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNextScore;
    private javax.swing.JButton jButtonPrevScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
